// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Hoa5ZGNJWbM6aqTqfLX43f6gNMCmGII',
    appId: '1:81381623914:web:5c0275c8d586343c3c6213',
    messagingSenderId: '81381623914',
    projectId: 'myrecipe-app-dee5c',
    authDomain: 'myrecipe-app-dee5c.firebaseapp.com',
    storageBucket: 'myrecipe-app-dee5c.firebasestorage.app',
    measurementId: 'G-GNJXK48QFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQxq-1RPlK6VsWEZQFgp2or4A2QHuqGuk',
    appId: '1:81381623914:android:aee03ef5b88145583c6213',
    messagingSenderId: '81381623914',
    projectId: 'myrecipe-app-dee5c',
    storageBucket: 'myrecipe-app-dee5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqRZvmZccDcA5_9_fYGObNgamI33ZjZqg',
    appId: '1:81381623914:ios:fc6fb6bb02d6b33b3c6213',
    messagingSenderId: '81381623914',
    projectId: 'myrecipe-app-dee5c',
    storageBucket: 'myrecipe-app-dee5c.firebasestorage.app',
    iosBundleId: 'com.example.myrecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqRZvmZccDcA5_9_fYGObNgamI33ZjZqg',
    appId: '1:81381623914:ios:fc6fb6bb02d6b33b3c6213',
    messagingSenderId: '81381623914',
    projectId: 'myrecipe-app-dee5c',
    storageBucket: 'myrecipe-app-dee5c.firebasestorage.app',
    iosBundleId: 'com.example.myrecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Hoa5ZGNJWbM6aqTqfLX43f6gNMCmGII',
    appId: '1:81381623914:web:c308d7b7254d03293c6213',
    messagingSenderId: '81381623914',
    projectId: 'myrecipe-app-dee5c',
    authDomain: 'myrecipe-app-dee5c.firebaseapp.com',
    storageBucket: 'myrecipe-app-dee5c.firebasestorage.app',
    measurementId: 'G-7H16CN03PJ',
  );
}
